### ISSUE TITLE
structural-pipeline-measures fails

### ISSUE THREAD

**Issue by yuniorcf** [amakropoulos/structural-pipeline-measures#4]
Hello, I am trying to run the pipeline but I don't get it to work. Please see below what I get in the terminal:
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
(base) yunior@pc-Neonat:~/DHCP/structural-pipeline-measures$ ./pipeline.sh /home/yunior/DHCP/data/derivatives/ /home/yunior/DHCP/data/dataset_11.csv --reporting
Reporting for the dHCP pipeline
Derivatives directory:  /home/yunior/DHCP/data/derivatives/ 
Dataset CSV:            /home/yunior/DHCP/data/dataset_11.csv

./pipeline.sh /home/yunior/DHCP/data/derivatives/ /home/yunior/DHCP/data/dataset_11.csv --reporting
----------------------------
computing volume/surface measurements of subjects...
subject-11 session-1

gathering volume/surface measurements of subjects...
cat: /home/yunior/DHCP/structural-pipeline-measures/reports/workdir/sub-subject-11_ses-session-1/sub-subject-11_ses-session-1-thickness: No such file or directory
cat: /home/yunior/DHCP/structural-pipeline-measures/reports/workdir/sub-subject-11_ses-session-1/sub-subject-11_ses-session-1-thickness-regions: No such file or directory
cat: /home/yunior/DHCP/structural-pipeline-measures/reports/workdir/sub-subject-11_ses-session-1/sub-subject-11_ses-session-1-sulc: No such file or directory
cat: /home/yunior/DHCP/structural-pipeline-measures/reports/workdir/sub-subject-11_ses-session-1/sub-subject-11_ses-session-1-sulc-regions: No such file or directory
cat: /home/yunior/DHCP/structural-pipeline-measures/reports/workdir/sub-subject-11_ses-session-1/sub-subject-11_ses-session-1-curvature: No such file or directory
cat: /home/yunior/DHCP/structural-pipeline-measures/reports/workdir/sub-subject-11_ses-session-1/sub-subject-11_ses-session-1-curvature-regions: No such file or directory
cat: /home/yunior/DHCP/structural-pipeline-measures/reports/workdir/sub-subject-11_ses-session-1/sub-subject-11_ses-session-1-GI: No such file or directory
cat: /home/yunior/DHCP/structural-pipeline-measures/reports/workdir/sub-subject-11_ses-session-1/sub-subject-11_ses-session-1-GI-regions: No such file or directory
cat: /home/yunior/DHCP/structural-pipeline-measures/reports/workdir/sub-subject-11_ses-session-1/sub-subject-11_ses-session-1-surface-area: No such file or directory
cat: /home/yunior/DHCP/structural-pipeline-measures/reports/workdir/sub-subject-11_ses-session-1/sub-subject-11_ses-session-1-surface-area-regions: No such file or directory
cat: /home/yunior/DHCP/structural-pipeline-measures/reports/workdir/sub-subject-11_ses-session-1/sub-subject-11_ses-session-1-rel-surface-area-regions: No such file or directory
completed volume/surface measurements
----------------------------

computing QC measurements for subjects...
subject-11 session-1

gathering QC measurements of subjects...
creating QC reports...
copying reports...
cp: cannot stat '/home/yunior/DHCP/structural-pipeline-measures/reports/anatomical_subject-11.pdf': No such file or directory
-------------------------------------------------------------------------------------------------------------------------------
-------------------------------------------------------------------------------------------------------------------------------
When looking to the error file it seems to have a problem to run mirtk (see attached files).

Additionally, to make it clear, I am unable to run the original pipeline for segmentation using for example the following command line:
./dhcp-pipeline.sh subject11 session1 34 -T2 subject11-T2.nii.gz -T1 subject11-T1.nii.gz -t 8 
it only work if i use instead:
$ sudo docker run --rm -t -u $(id -u):$(id -g) -v $PWD/data:/data biomedia/dhcp-structural-pipeline:latest subject11 session1 34 -T1 data/T1w.nii.gz -T2 data/T2w.nii.gz -t 8

I wonder whether is there a way to run structural-pipeline-measures by using a simmilar command line intead of the one posted in this web page

Thanks in advance

[subject-11-session-1-measures.log](https://github.com/amakropoulos/structural-pipeline-measures/files/3944681/subject-11-session-1-measures.log)
[subject-11-session-1-measures.err.txt](https://github.com/amakropoulos/structural-pipeline-measures/files/3944695/subject-11-session-1-measures.err.txt)

**Comment by feifei6699** [comment]
Hello, have you solved this problem? I met the same problem: "The left WM surface for subject sub-CC00099AN18_ses-34200 doesn't exist".

**Comment by yuniorcf-80** [comment]
Hi, unfortunately I was not able to run the structural-pipeline-measures sucessfully in my own machine. However I could made it work by using the following command:
sudo docker run --rm -t -v $PWD/data:/data -u $(id -u):$(id -g) biomedia/dhcp-structural-pipeline-measures:latest /data/participants.tsv --reporting 

hope it also works for you

**Comment by feifei6699** [comment]
Thanks so much for your helpful info!

**Comment by feifei6699** [comment]
> Hi, unfortunately I was not able to run the structural-pipeline-measures sucessfully in my own machine. However I could made it work by using the following command:
> sudo docker run --rm -t -v $PWD/data:/data -u $(id -u):$(id -g) biomedia/dhcp-structural-pipeline-measures:latest /data/participants.tsv --reporting
> 
> hope it also works for you



Hello, when I used the command: "sudo docker run --rm -t -v $PWD/data:/data -u $(id -u):$(id -g) biomedia/dhcp-structural-pipeline-measures:latest /data/participants.tsv --reporting", I had this problem:

Traceback (most recent call last):
  File "/usr/local/bin/structural_dhcp_mriqc", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.5/dist-packages/structural_dhcp_mriqc/utils/mriqc_run.py", line 144, in main
    run_id=opts.run_id, settings=settings)
  File "/usr/local/lib/python3.5/dist-packages/structural_dhcp_mriqc/workflows/core.py", line 49, in ms_anat_dhcp
    raise RuntimeError('No scans found in %s' % settings['dhcp_data'])
KeyError: 'dhcp_data'

Do you know how to solve this problem? Thanks for your time!

**Comment by moraesfernanda** [comment]
I am with the same problem with mirtk running natively. Do you have any suggestions for a version of this command "sudo docker run --rm -t -v (id -u):$(id -g) biomedia/dhcp-structural-pipeline-measures:latest /data/participants.tsv --reporting" out of docker?

**Comment by moraesfernanda** [comment]
Hi, i mange to fiz the erro by installing mirtk using
```
wget -O mirtk https://bintray.com/schuhschuh/AppImages/download_file?file_path=MIRTK%2Bview-latest-x86_64-glibc2.15.AppImage
chmod a+x mirtk
sudo mv mirtk /usr/bin
```
from their website https://mirtk.github.io/getstarted.html.
