### ISSUE TITLE
structural-pipeline-measures fails（ with docker image）

### ISSUE THREAD

**Issue by feifei6699** [amakropoulos/structural-pipeline-measures#5]
Hello,  I have successfully run the dhcp-structural-pipeline with the docker image. 
However, when I tried to run the structural-pipeline-measures with the docker image using the command:
**"sudo docker run --rm -t -v $PWD/data:/data -u $(id -u):$(id -g) biomedia/dhcp-structural-pipeline-measures:latest /data/participants.tsv --reporting"**
the error occurred

**feifei@feifei-virtual-machine:/var/lib/docker$ sudo docker run --rm -t -v $PWD/data:/data -u $(id -u):$(id -g) biomedia/dhcp-structural-pipeline-measures:latest /data/participants.tsv --reporting
Reporting for the dHCP pipeline

Derivatives directory: /data/derivatives
participants.tsv:      /data/participants.tsv
datadir:               /data
scriptdir:             /usr/src/structural-pipeline-measures/scripts
reportsdir:            /data/reports
logdir:                /data/logs
reporting:             1

/usr/src/structural-pipeline-measures/pipeline.sh /data/participants.tsv --reporting
----------------------------
CC00060XX03 bad gender 12501
computing volume/surface measurements of subjects...
gathering volume/surface measurements of subjects...
completed volume/surface measurements
----------------------------

computing QC measurements for subjects...

gathering QC measurements of subjects...
creating QC reports...
structural_dhcp_mriqc -o /data/reports -w /data/reports/workdir --dhcp-measures /data/reports/dhcp-measurements.json --qc-measures /data/reports/qc-measurements.json --nthreads 1 failed**

The "qc.err" file:
**Traceback (most recent call last):
  File "/usr/local/bin/structural_dhcp_mriqc", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.5/dist-packages/structural_dhcp_mriqc/utils/mriqc_run.py", line 144, in main
    run_id=opts.run_id, settings=settings)
  File "/usr/local/lib/python3.5/dist-packages/structural_dhcp_mriqc/workflows/core.py", line 37, in ms_anat_dhcp
    with open(settings['qc_measures'], 'r') as jsondata:
FileNotFoundError: [Errno 2] No such file or directory: '/data/reports/qc-measurements.json'
Traceback (most recent call last):
  File "/usr/local/bin/structural_dhcp_mriqc", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.5/dist-packages/structural_dhcp_mriqc/utils/mriqc_run.py", line 144, in main
    run_id=opts.run_id, settings=settings)
  File "/usr/local/lib/python3.5/dist-packages/structural_dhcp_mriqc/workflows/core.py", line 49, in ms_anat_dhcp
    raise RuntimeError('No scans found in %s' % settings['dhcp_data'])
KeyError: 'dhcp_data'**

How to deal with this problem?

Thanks in advance

**Comment by Thea-Eddie-Amy** [comment]
@feifei6699  Hi, have you solved the problem? I met the same situation as you did. Please let me know if you made some progress. Thanks!

**Comment by feifei6699** [comment]
> @feifei6699 Hi, have you solved the problem? I met the same situation as you did. Please let me know if you made some progress. Thanks!

Hi, I have solved the problem as followed,
   
        The "participants.tsv" should have lines like:

        participant_id  gender  birth_ga
        CC001              Female   44.0
        CC002              Male       42.0
         etc.
         
        There should not be a session number.

Hope it will help you!

**Comment by Thea-Eddie-Amy** [comment]
> > @feifei6699 Hi, have you solved the problem? I met the same situation as you did. Please let me know if you made some progress. Thanks!
> 
> Hi, I have solved the problem as followed,
> 
> ```
>     The "participants.tsv" should have lines like:
> 
>     participant_id  gender  birth_ga
>     CC001              Female   44.0
>     CC002              Male       42.0
>      etc.
>      
>     There should not be a session number.
> ```
> 
> Hope it will help you!

Thank you so much!! I managed to run the measure pipeline where I get all the results in workdir, however met some problems with QC reporting.
Here is the log&error:
`	 ***********************************
210313-02:56:23,564 workflow ERROR:
	 could not run node: anatMRIQC.MRIQC_Anat.plot_mosaic.a0
210313-02:56:23,565 workflow INFO:
	 crashfile: /30_0_liuwenting/reports/workdir_log/crash-20210313-025620-root-plot_mosaic.a0-89e57ee6-6105-4ff3-bc2c-7cc38a6fdd03.pklz
210313-02:56:23,565 workflow INFO:
	 ***********************************`

`Traceback (most recent call last):
  File "/usr/local/bin/structural_dhcp_mriqc", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.5/dist-packages/structural_dhcp_mriqc/utils/mriqc_run.py", line 146, in main
    workflow.run(**plugin_settings)
  File "/usr/local/lib/python3.5/dist-packages/nipype/pipeline/engine/workflows.py", line 595, in run
    runner.run(execgraph, updatehash=updatehash, config=self.config)
  File "/usr/local/lib/python3.5/dist-packages/nipype/pipeline/plugins/linear.py", line 61, in run
    report_nodes_not_run(notrun)
  File "/usr/local/lib/python3.5/dist-packages/nipype/pipeline/plugins/tools.py", line 81, in report_nodes_not_run
    raise RuntimeError(('Workflow did not execute cleanly. '
RuntimeError: Workflow did not execute cleanly. Check log for details`

I have no idea where went wrong, please help. Thanks!

**Comment by feifei6699** [comment]
> > > @feifei6699 Hi, have you solved the problem? I met the same situation as you did. Please let me know if you made some progress. Thanks!
> > 
> > 
> > Hi, I have solved the problem as followed,
> > ```
> >     The "participants.tsv" should have lines like:
> > 
> >     participant_id  gender  birth_ga
> >     CC001              Female   44.0
> >     CC002              Male       42.0
> >      etc.
> >      
> >     There should not be a session number.
> > ```
> > 
> > 
> > Hope it will help you!
> 
> Thank you so much!! I managed to run the measure pipeline where I get all the results in workdir, however met some problems with QC reporting.
> Here is the log&error:
> `	*********************************** 210313-02:56:23,564 workflow ERROR: could not run node: anatMRIQC.MRIQC_Anat.plot_mosaic.a0 210313-02:56:23,565 workflow INFO: crashfile: /30_0_liuwenting/reports/workdir_log/crash-20210313-025620-root-plot_mosaic.a0-89e57ee6-6105-4ff3-bc2c-7cc38a6fdd03.pklz 210313-02:56:23,565 workflow INFO: ***********************************`
> 
> `Traceback (most recent call last): File "/usr/local/bin/structural_dhcp_mriqc", line 11, in <module> sys.exit(main()) File "/usr/local/lib/python3.5/dist-packages/structural_dhcp_mriqc/utils/mriqc_run.py", line 146, in main workflow.run(**plugin_settings) File "/usr/local/lib/python3.5/dist-packages/nipype/pipeline/engine/workflows.py", line 595, in run runner.run(execgraph, updatehash=updatehash, config=self.config) File "/usr/local/lib/python3.5/dist-packages/nipype/pipeline/plugins/linear.py", line 61, in run report_nodes_not_run(notrun) File "/usr/local/lib/python3.5/dist-packages/nipype/pipeline/plugins/tools.py", line 81, in report_nodes_not_run raise RuntimeError(('Workflow did not execute cleanly. ' RuntimeError: Workflow did not execute cleanly. Check log for details`
> 
> I have no idea where went wrong, please help. Thanks!


I met the same problem, I had no idea too.
